--------------------------------------------------------------------------------
-- Automatically generated by vhdl_serdes -- DO NOT EDIT.
--
-- Record serialization helpers. Packing convention: the first field of a
-- record occupies the least significant bits, the last field the most
-- significant ones. A nested record is serialized through the functions
-- of the same naming convention.
--
-- Source(s):
--   examples/example_pkg.vhd
--------------------------------------------------------------------------------

library ieee;
  use ieee.std_logic_1164.all;
  use ieee.numeric_std.all;

use work.example_pkg.all;

package example_serdes_pkg is

  -----------------------------------------------------------------------------
  -- timestamp_t  (examples\example_pkg.vhd:15)
  -----------------------------------------------------------------------------
  -- Bit map, first field on the LSBs:
  --   [  31 :    0]  seconds : unsigned(31 downto 0)
  --   [  47 :   32]  ticks : unsigned(15 downto 0)
  --   total: 48 bits
  constant TIMESTAMP_SERIALIZED_WIDTH : natural := 32 + 16;  -- 48 bits

  function timestamp_record2slv (value : timestamp_t) return std_logic_vector;
  function timestamp_slv2record (data : std_logic_vector) return timestamp_t;

  -----------------------------------------------------------------------------
  -- header_t  (examples\example_pkg.vhd:21)
  -----------------------------------------------------------------------------
  -- Bit map, first field on the LSBs:
  --   [   3 :    0]  version : unsigned(3 downto 0)
  --   [  11 :    4]  kind : byte_t
  --   [  59 :   12]  stamp : timestamp_t
  --   [  60 :   60]  valid : std_logic
  --   total: 61 bits
  constant HEADER_SERIALIZED_WIDTH : natural := 4 + 8 + TIMESTAMP_SERIALIZED_WIDTH + 1;  -- 61 bits

  function header_record2slv (value : header_t) return std_logic_vector;
  function header_slv2record (data : std_logic_vector) return header_t;

  -----------------------------------------------------------------------------
  -- frame_t  (examples\example_pkg.vhd:29)
  -----------------------------------------------------------------------------
  -- Bit map, first field on the LSBs:
  --   [  60 :    0]  hdr : header_t
  --   [+((DATA_W - 1) + 1)]  data : std_logic_vector(DATA_W - 1 downto 0)
  --   [+         12]  offset : signed(11 downto 0)
  --   [+          1]  last : std_logic
  constant FRAME_SERIALIZED_WIDTH : natural := HEADER_SERIALIZED_WIDTH + ((DATA_W - 1) + 1) + 12 + 1;

  function frame_record2slv (value : frame_t) return std_logic_vector;
  function frame_slv2record (data : std_logic_vector) return frame_t;

end package example_serdes_pkg;

package body example_serdes_pkg is

  -----------------------------------------------------------------------------
  -- timestamp_t
  -----------------------------------------------------------------------------
  constant TIMESTAMP_SECONDS_LOW  : natural := 0;
  constant TIMESTAMP_SECONDS_HIGH : natural := TIMESTAMP_SECONDS_LOW + 31;
  constant TIMESTAMP_TICKS_LOW    : natural := TIMESTAMP_SECONDS_HIGH + 1;
  constant TIMESTAMP_TICKS_HIGH   : natural := TIMESTAMP_TICKS_LOW + 15;

  function timestamp_record2slv (value : timestamp_t) return std_logic_vector is
    variable result : std_logic_vector(TIMESTAMP_SERIALIZED_WIDTH - 1 downto 0);
  begin
    result(TIMESTAMP_SECONDS_HIGH downto TIMESTAMP_SECONDS_LOW) := std_logic_vector(value.seconds);
    result(TIMESTAMP_TICKS_HIGH downto TIMESTAMP_TICKS_LOW)     := std_logic_vector(value.ticks);
    return result;
  end function timestamp_record2slv;

  function timestamp_slv2record (data : std_logic_vector) return timestamp_t is
    variable src    : std_logic_vector(TIMESTAMP_SERIALIZED_WIDTH - 1 downto 0);
    variable result : timestamp_t;
  begin
    assert data'length = TIMESTAMP_SERIALIZED_WIDTH
      report "timestamp_slv2record: expected " & integer'image(TIMESTAMP_SERIALIZED_WIDTH)
             & " bits, got " & integer'image(data'length)
      severity failure;
    src := data;
    result.seconds := unsigned(src(TIMESTAMP_SECONDS_HIGH downto TIMESTAMP_SECONDS_LOW));
    result.ticks   := unsigned(src(TIMESTAMP_TICKS_HIGH downto TIMESTAMP_TICKS_LOW));
    return result;
  end function timestamp_slv2record;

  -----------------------------------------------------------------------------
  -- header_t
  -----------------------------------------------------------------------------
  constant HEADER_VERSION_LOW  : natural := 0;
  constant HEADER_VERSION_HIGH : natural := HEADER_VERSION_LOW + 3;
  constant HEADER_KIND_LOW     : natural := HEADER_VERSION_HIGH + 1;
  constant HEADER_KIND_HIGH    : natural := HEADER_KIND_LOW + 7;
  constant HEADER_STAMP_LOW    : natural := HEADER_KIND_HIGH + 1;
  constant HEADER_STAMP_HIGH   : natural := HEADER_STAMP_LOW + TIMESTAMP_SERIALIZED_WIDTH - 1;
  constant HEADER_VALID_LOW    : natural := HEADER_STAMP_HIGH + 1;

  function header_record2slv (value : header_t) return std_logic_vector is
    variable result : std_logic_vector(HEADER_SERIALIZED_WIDTH - 1 downto 0);
  begin
    result(HEADER_VERSION_HIGH downto HEADER_VERSION_LOW) := std_logic_vector(value.version);
    result(HEADER_KIND_HIGH downto HEADER_KIND_LOW)       := value.kind;
    result(HEADER_STAMP_HIGH downto HEADER_STAMP_LOW)     := timestamp_record2slv(value.stamp);
    result(HEADER_VALID_LOW)                              := value.valid;
    return result;
  end function header_record2slv;

  function header_slv2record (data : std_logic_vector) return header_t is
    variable src    : std_logic_vector(HEADER_SERIALIZED_WIDTH - 1 downto 0);
    variable result : header_t;
  begin
    assert data'length = HEADER_SERIALIZED_WIDTH
      report "header_slv2record: expected " & integer'image(HEADER_SERIALIZED_WIDTH)
             & " bits, got " & integer'image(data'length)
      severity failure;
    src := data;
    result.version := unsigned(src(HEADER_VERSION_HIGH downto HEADER_VERSION_LOW));
    result.kind    := src(HEADER_KIND_HIGH downto HEADER_KIND_LOW);
    result.stamp   := timestamp_slv2record(src(HEADER_STAMP_HIGH downto HEADER_STAMP_LOW));
    result.valid   := src(HEADER_VALID_LOW);
    return result;
  end function header_slv2record;

  -----------------------------------------------------------------------------
  -- frame_t
  -----------------------------------------------------------------------------
  constant FRAME_HDR_LOW     : natural := 0;
  constant FRAME_HDR_HIGH    : natural := FRAME_HDR_LOW + HEADER_SERIALIZED_WIDTH - 1;
  constant FRAME_DATA_LOW    : natural := FRAME_HDR_HIGH + 1;
  constant FRAME_DATA_HIGH   : natural := FRAME_DATA_LOW + ((DATA_W - 1) + 1) - 1;
  constant FRAME_OFFSET_LOW  : natural := FRAME_DATA_HIGH + 1;
  constant FRAME_OFFSET_HIGH : natural := FRAME_OFFSET_LOW + 11;
  constant FRAME_LAST_LOW    : natural := FRAME_OFFSET_HIGH + 1;

  function frame_record2slv (value : frame_t) return std_logic_vector is
    variable result : std_logic_vector(FRAME_SERIALIZED_WIDTH - 1 downto 0);
  begin
    result(FRAME_HDR_HIGH downto FRAME_HDR_LOW)       := header_record2slv(value.hdr);
    result(FRAME_DATA_HIGH downto FRAME_DATA_LOW)     := value.data;
    result(FRAME_OFFSET_HIGH downto FRAME_OFFSET_LOW) := std_logic_vector(value.offset);
    result(FRAME_LAST_LOW)                            := value.last;
    return result;
  end function frame_record2slv;

  function frame_slv2record (data : std_logic_vector) return frame_t is
    variable src    : std_logic_vector(FRAME_SERIALIZED_WIDTH - 1 downto 0);
    variable result : frame_t;
  begin
    assert data'length = FRAME_SERIALIZED_WIDTH
      report "frame_slv2record: expected " & integer'image(FRAME_SERIALIZED_WIDTH)
             & " bits, got " & integer'image(data'length)
      severity failure;
    src := data;
    result.hdr    := header_slv2record(src(FRAME_HDR_HIGH downto FRAME_HDR_LOW));
    result.data   := src(FRAME_DATA_HIGH downto FRAME_DATA_LOW);
    result.offset := signed(src(FRAME_OFFSET_HIGH downto FRAME_OFFSET_LOW));
    result.last   := src(FRAME_LAST_LOW);
    return result;
  end function frame_slv2record;

end package body example_serdes_pkg;
